# -*- coding: utf-8 -*-
"""task2_portfolio_tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4KqATywmVUVoT9buj9jVi1rt8J1c9lY
"""

"""
Task 2: Stock Portfolio Tracker
Description: Calculates total investment based on manually defined stock prices
and quantities, then outputs a summary text file.
"""

def track_portfolio():
    stock_prices = {
        "AAPL": 180.50,
        "TSLA": 250.00,
        "MSFT": 330.25,
        "GOOG": 140.00
    }

    total_investment = 0.0
    portfolio_summary = []

    print("--- Stock Portfolio Tracker ---")
    print("Available stocks: AAPL, TSLA, MSFT, GOOG")

    while True:
        ticker = input("\nEnter the stock ticker (or type 'quit' to finish): ").upper()

        if ticker == 'QUIT':
            break

        if ticker in stock_prices:
            try:
                quantity = float(input(f"How many shares of {ticker} do you own? "))
            except ValueError:
                print("Invalid input. Please enter a number.")
                continue

            price = stock_prices[ticker]
            value = price * quantity
            total_investment += value

            record = f"{ticker}: {quantity} shares @ ${price} = ${value:.2f}"
            portfolio_summary.append(record)
            print(f"Added! Current Total Investment: ${total_investment:.2f}")

        else:
            print("Stock not found in our database. Try again.")

    print("\n--- Final Portfolio Summary ---")
    summary_text = "\n".join(portfolio_summary)
    print(summary_text)
    print(f"Total Portfolio Value: ${total_investment:.2f}")

    save = input("\nWould you like to save this to a file? (y/n): ").lower()
    if save == 'y':
        with open("portfolio_summary.txt", "w") as file:
            file.write("Portfolio Summary\n")
            file.write("-" * 20 + "\n")
            file.write(summary_text + "\n")
            file.write("-" * 20 + "\n")
            file.write(f"Total Value: ${total_investment:.2f}\n")
        print("Saved to portfolio_summary.txt")

if __name__ == "__main__":
    track_portfolio()