# -*- coding: utf-8 -*-
"""task1_hangman.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G5QEPf5RLlg6hTf1CKacGWl4vtWixkS8
"""

import random

def play_hangman():
    # 1. Setup Data
    word_list = ["engine", "torque", "vector", "stator", "design"]
    secret_word = random.choice(word_list)
    guessed_letters = []
    incorrect_guesses_left = 6

    print("Welcome to Hangman!")

    # 2. Main Game Loop
    while incorrect_guesses_left > 0:
        # Build the current state of the word (e.g., _ n g _ n _)
        display_word = ""
        for letter in secret_word:
            if letter in guessed_letters:
                display_word += letter + " "
            else:
                display_word += "_ "

        print(f"\nWord: {display_word}")
        print(f"Incorrect guesses remaining: {incorrect_guesses_left}")

        # Check for win condition
        if "_" not in display_word:
            print("Congratulations! You guessed the word!")
            return # Exits the function/game

        # 3. User Input
        guess = input("Guess a letter: ").lower()

        # 4. Logic/Verification
        if len(guess) != 1 or not guess.isalpha():
            print("Please enter a single valid letter.")
            continue

        if guess in guessed_letters:
            print("You already guessed that letter.")
            continue

        guessed_letters.append(guess)

        if guess not in secret_word:
            incorrect_guesses_left -= 1
            print(f"Wrong! '{guess}' is not in the word.")
        else:
            print(f"Good job! '{guess}' is in the word.")

    # 5. Loss condition
    print(f"\nGame Over! You ran out of guesses. The word was '{secret_word}'.")

# Run the game
play_hangman()