# -*- coding: utf-8 -*-
"""task4_chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4TOBbMwTL2EUFJEbcDWoBa3d5kgskH2
"""

"""
Task 4: Basic Rule-Based Chatbot
Description: A simple loop that takes user input and returns predefined
greetings and farewells.
"""

def get_bot_response(user_message):
    message = user_message.lower().strip()

    if message in ["hello", "hi"]:
        return "Hi!"
    elif message in ["how are you", "how are you?"]:
        return "I'm fine, thanks!"
    elif message in ["bye", "goodbye"]:
        return "Goodbye!"
    else:
        return "I'm sorry, I don't understand. Try 'hello', 'how are you', or 'bye'."

def start_chat():
    print("Chatbot activated. Type 'bye' to exit.")
    print("-" * 30)

    while True:
        user_input = input("You: ")
        bot_reply = get_bot_response(user_input)
        print(f"Bot: {bot_reply}")

        if user_input.lower().strip() in ["bye", "goodbye"]:
            break

if __name__ == "__main__":
    start_chat()